//import java.util.Comparator;
//import java.util.LinkedList;

public class Main {
    public static void main(String[] args) {
        implementation();

    }

    public static void implementation() {
        LinkedList<Integer> list = new LinkedList<>();
        list.addFirst(35);
        list.add(1, 93);
        list.add(0, 82);
        list.add(0, 20);
        list.addLast(57);
        list.addLast(19);
        list.add(0, 0);
        list.addFirst(47);
        list.add(7, 89);
        list.addFirst(80);
        list.add(8, 71);
        list.size();
        list.isEmpty();
        list.add(1, 12);
        list.get(2);
        list.getLast();
        list.get(10);
        list.get(2);
        list.getFirst();
        list.getFirst();
        list.getLast();
        list.addLast(81);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addFirst(35);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(740);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(741);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(7);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(75);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.addLast(745);
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeFirst();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.removeLast();
        list.add(4, 0);
        list.add(1, 0);
        list.add(23, 0);
        list.add(32, 0);
        list.add(5, 0);
        list.add(56, 0);
        list.add(6, 0);
        list.add(62, 0);
        list.add(61, 0);
        list.add(5, 0);
        list.add(53, 0);
        list.add(46, 0);
        list.add(49, 0);
        list.add(4, 0);
        list.add(47, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(4, 0);
        list.add(43, 0);
        list.add(35, 0);
        list.add(1, 0);
        list.add(49, 0);
        list.add(44, 0);
        list.add(53, 0);
        list.add(34, 0);
        list.add(9, 0);
        list.add(42, 0);
        list.add(41, 0);
        list.add(5, 0);
        list.add(4, 0);
        list.add(8, 0);
        list.add(9, 0);
        list.add(123, 0);
        list.add(78, 0);
        list.add(14, 0);
        list.add(40, 0);

        list.remove(43);
        list.remove(43);
        list.remove(43);

        list.remove(43);
        list.remove(23);
        list.remove(11);
        list.remove(0);
        list.remove(134);
        list.remove(22);
        list.remove(99);
        list.remove(79);
        list.remove(23);
        list.remove(42);
        list.remove(25);
        list.remove(10);
        list.remove(11);
        list.remove(12);
        list.remove(46);
        list.remove(33);
        list.remove(13);
        list.remove(23);
        list.remove(3);
        list.remove(90);
        list.remove(47);
        list.remove(4);
        list.remove(46);
        list.remove(43);
        System.out.println();
        System.out.println(list.size());
        System.out.println(System.currentTimeMillis());

        System.out.println();


    }

}